NoPermission: "&cYou are not allowed to do this."
Lines: 3
Message-1: "&c&lThank you for download my plugin. &b&lbyDekei"
Message-2: "&6&l:D &e&l%player% &6&l:D"
Message-3: "&c&lYou can support me on: &e&lhttps://goo.gl/3Opm65"
Message-4: ""
Message-5: ""